# Generated by Django 3.0 on 2022-12-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate_Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile_number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('years_of_experience', models.CharField(blank=True, choices=[('Fresher', 'Fresher'), ('Less than a year', 'Less than a year'), ('1 - 2 years', '1 - 2 years'), ('2 - 4 years', '2 - 4 years'), ('4 - 7 years', '4 - 7 years'), ('7 - 10 years', '7 - 10 years'), ('10+ years', '10+ years')], max_length=30, null=True)),
                ('years_of_relevant_experience', models.CharField(blank=True, choices=[('Fresher', 'Fresher'), ('Less than a year', 'Less than a year'), ('1 - 2 years', '1 - 2 years'), ('2 - 4 years', '2 - 4 years'), ('4 - 7 years', '4 - 7 years'), ('7 - 10 years', '7 - 10 years'), ('10+ years', '10+ years')], max_length=30, null=True)),
                ('resume', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address_Proof', models.FileField(upload_to='')),
                ('Photo_Identity_Proof', models.FileField(upload_to='')),
                ('SSC_Certificate', models.FileField(upload_to='')),
                ('HSC_Certificate', models.FileField(upload_to='')),
                ('Diploma_Certificate', models.FileField(upload_to='')),
                ('Degree_Certificate', models.FileField(upload_to='')),
                ('PG_Certificate', models.FileField(upload_to='')),
                ('College_TC', models.FileField(upload_to='')),
                ('Passport_Size_Photograph', models.FileField(upload_to='')),
                ('Casual_Photograph', models.FileField(upload_to='')),
                ('Bank_Passbook', models.FileField(upload_to='')),
                ('Internship_Certificate', models.FileField(upload_to='')),
                ('Experience_Certificate', models.FileField(upload_to='')),
                ('Last_3_Salary_Slips', models.FileField(upload_to='')),
                ('Form_16', models.FileField(upload_to='')),
                ('Passport', models.FileField(upload_to='')),
                ('Covid_Vaccination_Certificate', models.FileField(upload_to='')),
                ('Medical_Certificate', models.FileField(upload_to='')),
                ('Police_Verification_Document', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requestor_name', models.CharField(max_length=30)),
                ('project_name', models.CharField(blank=True, choices=[('project name 1', 'project name 1'), ('project name 2', 'project name 2'), ('project name 3', 'project name 3')], max_length=40, null=True)),
                ('resource_designation', models.CharField(blank=True, choices=[('senior software developer', 'senior software developer'), ('junior software developer', 'junior software developer'), ('software developer trainee', 'software developer trainee')], max_length=30, null=True)),
                ('department', models.CharField(blank=True, choices=[('CCMS', 'CCMS'), ('Library', 'Library'), ('HR', 'HR'), ('Non-Academic', 'Non-Academic'), ('RFC', 'RFC'), ('RF-Campus', 'RF-Campus'), ('Sales', 'Sales')], max_length=30, null=True)),
                ('type_of_resource', models.CharField(blank=True, choices=[('Payroll', 'Payroll'), ('Intern', 'Intern')], max_length=30, null=True)),
                ('posting_location', models.CharField(blank=True, choices=[('Nagpur', 'Nagpur'), ('Pune', 'Pune'), ('Mumbai', 'Mumbai'), ('Aurangabad', 'Aurangabad')], max_length=30, null=True)),
                ('experience_required', models.IntegerField()),
                ('job_description', models.CharField(max_length=100)),
                ('special_remark', models.CharField(max_length=100)),
                ('recommended_by', models.CharField(max_length=100)),
            ],
        ),
    ]
