# Generated by Django 3.0 on 2022-12-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='requiremnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestor_name', models.CharField(max_length=30)),
                ('project_name', models.CharField(blank=True, choices=[('project name 1', 'project name 1'), ('project name 2', 'project name 2'), ('project name 3', 'project name 3')], max_length=40, null=True)),
                ('resource_designation', models.CharField(blank=True, choices=[('senior software developer', 'senior software developer'), ('junior software developer', 'junior software developer'), ('software developer trainee', 'software developer trainee')], max_length=30, null=True)),
                ('department', models.CharField(blank=True, choices=[('CCMS', 'CCMS'), ('Library', 'Library'), ('HR', 'HR'), ('Non-Academic', 'Non-Academic'), ('RFC', 'RFC'), ('RF-Campus', 'RF-Campus'), ('Sales', 'Sales')], max_length=30, null=True)),
                ('type_of_resource', models.CharField(blank=True, choices=[('Payroll', 'Payroll'), ('Intern', 'Intern')], max_length=30, null=True)),
                ('posting_location', models.CharField(blank=True, choices=[('Nagpur', 'Nagpur'), ('Pune', 'Pune'), ('Mumbai', 'Mumbai'), ('Aurangabad', 'Aurangabad')], max_length=30, null=True)),
                ('experience_required', models.IntegerField()),
                ('job_description', models.CharField(max_length=100)),
                ('special_remark', models.CharField(max_length=100)),
                ('recommended_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='requirement',
        ),
    ]
