# Generated by Django 3.0 on 2022-12-21 06:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0002_auto_20221221_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='requiremnt',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 6, 59, 16, 644871, tzinfo=utc), verbose_name=datetime.datetime(2022, 12, 21, 6, 59, 7, 64363, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
