# Generated by Django 3.0 on 2022-12-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0003_requiremnt_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requiremnt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
