# Generated by Django 3.0 on 2022-12-21 07:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0004_auto_20221221_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requiremnt',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 7, 8, 19, 905082, tzinfo=utc)),
        ),
    ]
