# Generated by Django 3.0 on 2022-12-21 09:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0005_auto_20221221_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requiremnt',
            name='recommended_by',
        ),
        migrations.AlterField(
            model_name='requiremnt',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 9, 15, 18, 107943, tzinfo=utc)),
        ),
    ]
