# Generated by Django 3.0 on 2022-12-22 06:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0007_auto_20221221_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='no_of_positions',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 6, 14, 11, 883462, tzinfo=utc)),
        ),
    ]
