# Generated by Django 3.0 on 2022-12-22 07:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0008_auto_20221222_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='job_description',
            new_name='technologies_required',
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 7, 19, 31, 458834, tzinfo=utc)),
        ),
    ]
