# Generated by Django 3.0 on 2022-12-22 07:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0009_auto_20221222_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 7, 42, 11, 99113, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='resource_designation',
            field=models.CharField(blank=True, choices=[('Senior Software Developer', 'Senior Software Developer'), ('Junior Software Developer', 'Junior Software Developer'), ('Software Developer Trainee', 'Software Developer Trainee')], max_length=30, null=True),
        ),
    ]
