# Generated by Django 3.0 on 2022-12-22 09:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0010_auto_20221222_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 22, 9, 2, 48, 168733, tzinfo=utc)),
        ),
    ]
