# Generated by Django 3.0 on 2022-12-22 12:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0012_auto_20221222_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_application',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 22, 12, 0, 34, 852406, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 22, 12, 0, 34, 852406, tzinfo=utc)),
        ),
    ]
