# Generated by Django 3.0 on 2022-12-23 07:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0014_auto_20221223_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied_for_accounts',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 23, 7, 43, 19, 847351, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applied_for_development',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 23, 7, 43, 19, 847351, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applied_for_hr',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 23, 7, 43, 19, 847351, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applied_for_it',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 23, 7, 43, 19, 847351, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applied_for_sales',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 23, 7, 43, 19, 847351, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 23, 7, 43, 19, 847351, tzinfo=utc)),
        ),
    ]
