# Generated by Django 3.0 on 2022-12-23 07:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0015_auto_20221223_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applied_for_development',
            options={'verbose_name_plural': 'Applied For Development'},
        ),
        migrations.AlterField(
            model_name='applied_for_accounts',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 23, 7, 45, 35, 559727, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applied_for_development',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 23, 7, 45, 35, 559727, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applied_for_hr',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 23, 7, 45, 35, 559727, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applied_for_it',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 23, 7, 45, 35, 559727, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applied_for_sales',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 23, 7, 45, 35, 559727, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 23, 7, 45, 35, 559727, tzinfo=utc)),
        ),
    ]
