# Generated by Django 3.0 on 2022-12-23 09:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0016_auto_20221223_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applied_for_accounts',
            options={'verbose_name_plural': 'Candidate Applied For Accounts'},
        ),
        migrations.AlterModelOptions(
            name='applied_for_development',
            options={'verbose_name_plural': 'Candidate Applied For Development'},
        ),
        migrations.AlterModelOptions(
            name='applied_for_hr',
            options={'verbose_name_plural': 'Candidate Applied For HR'},
        ),
        migrations.AlterModelOptions(
            name='applied_for_sales',
            options={'verbose_name_plural': 'Candidate Applied For Sales'},
        ),
        migrations.AlterField(
            model_name='applied_for_accounts',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 23, 9, 44, 4, 548477, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applied_for_development',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 23, 9, 44, 4, 548477, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applied_for_hr',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 23, 9, 44, 4, 548477, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applied_for_it',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 23, 9, 44, 4, 548477, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applied_for_sales',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 23, 9, 44, 4, 548477, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 23, 9, 44, 4, 548477, tzinfo=utc)),
        ),
    ]
