# Generated by Django 3.0 on 2022-12-27 05:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0017_auto_20221223_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='optional_interviewer_bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('mobile_number', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Optional Interviewer Bank',
            },
        ),
        migrations.AlterModelOptions(
            name='applied_for_it',
            options={'verbose_name_plural': 'Candidate Applied For IT'},
        ),
        migrations.AlterField(
            model_name='applied_for_accounts',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 27, 5, 33, 47, 669383, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applied_for_development',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 27, 5, 33, 47, 669383, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applied_for_hr',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 27, 5, 33, 47, 669383, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applied_for_it',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 27, 5, 33, 47, 669383, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applied_for_sales',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 27, 5, 33, 47, 669383, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 27, 5, 33, 47, 669383, tzinfo=utc)),
        ),
    ]
