# Generated by Django 3.0 on 2022-12-28 11:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0018_auto_20221227_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='budget',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='applied_for_accounts',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 28, 11, 3, 31, 511129, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applied_for_development',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 28, 11, 3, 31, 511129, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applied_for_hr',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 28, 11, 3, 31, 511129, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applied_for_it',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 28, 11, 3, 31, 511129, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applied_for_sales',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 28, 11, 3, 31, 511129, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 28, 11, 3, 31, 511129, tzinfo=utc)),
        ),
    ]
