# Generated by Django 3.0 on 2023-01-02 09:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0020_auto_20230102_1430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='applied_for_accounts',
        ),
        migrations.DeleteModel(
            name='applied_for_development',
        ),
        migrations.DeleteModel(
            name='applied_for_hr',
        ),
        migrations.DeleteModel(
            name='applied_for_IT',
        ),
        migrations.DeleteModel(
            name='applied_for_sales',
        ),
        migrations.AddField(
            model_name='candidate_application',
            name='department',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate_application',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 2, 9, 33, 20, 322519, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 2, 9, 33, 20, 322519, tzinfo=utc)),
        ),
    ]
