# Generated by Django 3.0 on 2023-01-03 05:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0022_auto_20230102_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduled_interview',
            options={'verbose_name_plural': 'Scheduled Interview of Candidates'},
        ),
        migrations.AlterField(
            model_name='candidate_application',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 3, 5, 14, 39, 997268, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 3, 5, 14, 39, 997268, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
