# Generated by Django 3.0 on 2023-01-03 05:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0023_auto_20230103_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_application',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 3, 5, 16, 30, 157117, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 3, 5, 16, 30, 157117, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name=datetime.datetime(2023, 1, 3, 5, 16, 30, 157117, tzinfo=utc)),
        ),
    ]
