# Generated by Django 3.0 on 2023-01-03 07:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0030_auto_20230103_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_application',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 3, 7, 18, 37, 405105, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 3, 7, 18, 37, 389460, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='google_meet_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='mode',
            field=models.CharField(blank=True, choices=[('online', 'online'), ('offline', 'offline')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 3, 7, 18, 37, 405105, tzinfo=utc)),
        ),
    ]
