# Generated by Django 3.0 on 2023-01-04 09:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0032_auto_20230103_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='selected_candidate_interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact_no', models.DecimalField(decimal_places=0, max_digits=10)),
                ('department', models.CharField(max_length=100)),
                ('created_at', models.DateField(default=datetime.datetime(2023, 1, 4, 9, 33, 55, 926919, tzinfo=utc))),
                ('resume', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'selected candidate for interview',
            },
        ),
        migrations.AlterField(
            model_name='candidate_application',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 4, 9, 33, 55, 926919, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 4, 9, 33, 55, 926919, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 4, 9, 33, 55, 926919, tzinfo=utc)),
        ),
    ]
