# Generated by Django 3.0 on 2023-01-04 09:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0033_auto_20230104_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selected_candidate_interview',
            old_name='name',
            new_name='your_name',
        ),
        migrations.AlterField(
            model_name='candidate_application',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 4, 9, 45, 57, 35499, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 4, 9, 45, 57, 35499, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 4, 9, 45, 57, 35499, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='selected_candidate_interview',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 4, 9, 45, 57, 35499, tzinfo=utc)),
        ),
    ]
