# Generated by Django 3.0 on 2023-01-05 11:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0037_auto_20230105_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduled_interview',
            name='interviewer_bank',
        ),
        migrations.AlterField(
            model_name='candidate_application',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 5, 11, 58, 41, 67593, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 5, 11, 58, 41, 67593, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 5, 11, 58, 41, 83176, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='selected_candidate_interview',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 5, 11, 58, 41, 83176, tzinfo=utc)),
        ),
    ]
