# Generated by Django 3.0 on 2023-01-05 12:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0038_auto_20230105_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduled_interview',
            name='choice_field',
            field=models.CharField(blank=True, choices=[('Amol Gahukar', 'amol.gahukar@mastersofterp.co.in'), ('Ritesh Singh', 'mis.mumbai@iitms.co.in'), ('Pushpendra Verma', 'pushpendra.verma@mastersofterp.co.in'), ('POONAM BENDE', 'poonam.bende@mastersofterp.co.in'), ('Rakesh Upadhyay', 'rakesh.singh@mastersofterp.co.in'), ('Rutika Nilamwar', 'rutika.nilamwar@iitms.co.in'), ('Rahid Sajeel Iqbal Ahmed', 'rahid.sajeel@mastersofterp.co.in'), ('PRASHANT WANKAR', 'prashant.wankar@mastersofterp.co.in'), ('SHRIKANT BHARNE', 'shrikant.bharne@mastersofterp.co.in'), ('Lakhan Mangtani', 'lakhan.mangtani@mastersofterp.co.in'), ('Annie Biju Thomas', 'annie.thomas@mastersofterp.co.in'), ('Gaurav Kalbande', 'gaurav.kalbande@mastersofterp.co.in'), ('ROSHAN PANNASE', 'roshan.pannase@mastersofterp.co.in'), ('Sarang Mutkure', 'sarang.mutkure@mastersofterp.co.in'), ('SALMAN IRFAN KHAN', 'salman.khan@mastersofterp.co.in'), ('Paras Palsatkar', 'paras.palsatkar@mastersofterp.co.in'), ('MUSTAK MOHAMMAD BASHIR ROGATYA', 'mustak@iitms.co.in'), ('Mahima Jhavar', 'mahima.j@iitms.co.in'), ('Khushboo Sheikh', 'khushboo.sheikh@mastersofterp.co.in'), ('Ankit Bajaj', 'ankit.bajaj@iitms.co.in'), ('Digvijay Shinge', 'digvijay.shinge@iitms.co.in'), ('R. KRISHNA KUMAR', 'krishnakumar@iitms.co.in'), ('Siddharth Chaudhary', 'siddharth.chaudhary@mastersofterp.co.in'), ('CHHAGAN SATWANE', 'chhagan.satawne@mastersofterp.co.in'), ('ANKUSH TAWAR', 'ankush.tawar@mastersofterp.co.in')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_application',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 5, 12, 55, 42, 718371, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 5, 12, 55, 42, 718371, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 5, 12, 55, 42, 839929, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='selected_candidate_interview',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 5, 12, 55, 42, 839929, tzinfo=utc)),
        ),
    ]
