# Generated by Django 3.0 on 2023-01-05 12:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0039_auto_20230105_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduled_interview',
            name='choice_field',
        ),
        migrations.AlterField(
            model_name='candidate_application',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 5, 12, 59, 37, 875544, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 5, 12, 59, 37, 859862, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 5, 12, 59, 37, 875544, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='selected_candidate_interview',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 5, 12, 59, 37, 875544, tzinfo=utc)),
        ),
    ]
