# Generated by Django 3.0 on 2023-01-11 09:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0043_auto_20230111_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_application',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 11, 9, 55, 5, 425305, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 11, 9, 55, 5, 425305, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='department',
            field=models.CharField(blank=True, choices=[('BUSINESS DEVELOPMENT', 'BUSINESS DEVELOPMENT'), ('DEVELOPMENT', 'DEVELOPMENT'), ('HR', 'HR'), ('TESTER ', ' TESTER '), ('IMPLEMENTATION (CCMS)', 'IMPLEMENTATION (CCMS)'), ('CCMS (OTHER)', 'CCMS (OTHER)'), ('IMPLEMENTATION (RFC)', 'IMPLEMENTATION (RFC)'), ('WEB', 'WEB'), ('DIGITAL MARKETING', 'DIGITAL MARKETING'), ('MARKETING', 'PRE-MARKETING'), ('ACCOUNTS', 'ACCOUNTS'), ('ADMIN', 'ADMIN'), ('TECH IT', ' TECH IT'), ('MANAGEMENT', 'MANAGEMENT')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='resource_designation',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 11, 9, 55, 5, 425305, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='selected_candidate_interview',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 11, 9, 55, 5, 425305, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='test_model',
            name='department',
            field=models.CharField(blank=True, choices=[('BUSINESS DEVELOPMENT', 'BUSINESS DEVELOPMENT'), ('HR', 'HR'), ('MARKETING', 'MARKETING')], max_length=100, null=True),
        ),
    ]
