# Generated by Django 3.0 on 2023-01-11 12:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0045_auto_20230111_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='resource_designation',
            new_name='position',
        ),
        migrations.AlterField(
            model_name='candidate_application',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 11, 12, 57, 13, 814933, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 11, 12, 57, 13, 814933, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 11, 12, 57, 13, 830557, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='selected_candidate_interview',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 11, 12, 57, 13, 830557, tzinfo=utc)),
        ),
    ]
