# Generated by Django 3.0 on 2023-01-12 07:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0057_auto_20230112_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_application',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 12, 7, 19, 7, 432902, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 12, 7, 19, 7, 432902, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='department',
            field=models.CharField(blank=True, choices=[('BUSINESS_DEVELOPMENT', 'BUSINESS DEVELOPMENT'), ('DEVELOPMENT', 'DEVELOPMENT'), ('HR', 'HR'), ('TESTER', 'TESTER'), ('IMPLEMENTATION_CCMS', 'IMPLEMENTATION_CCMS'), ('CCMS_OTHER', 'CCMS OTHER'), ('IMPLEMENTATION_RFC', 'IMPLEMENTATION RFC'), ('WEB', 'WEB'), ('DIGITAL_MARKETING', 'DIGITAL MARKETING'), ('MARKETING', 'PRE-MARKETING'), ('ACCOUNTS', 'ACCOUNTS'), ('ADMIN', 'ADMIN'), ('TECH_IT', 'TECH IT'), ('MANAGEMENT', 'MANAGEMENT')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 12, 7, 19, 7, 432902, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='selected_candidate_interview',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 12, 7, 19, 7, 432902, tzinfo=utc)),
        ),
    ]
