# Generated by Django 3.0 on 2023-01-13 09:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0059_auto_20230112_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_application',
            name='current_ctc',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate_application',
            name='expected_ctc',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate_application',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 13, 9, 0, 0, 33266, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 13, 9, 0, 0, 33266, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 13, 9, 0, 0, 33266, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='selected_candidate_interview',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 13, 9, 0, 0, 33266, tzinfo=utc)),
        ),
    ]
