# Generated by Django 3.0 on 2023-01-17 07:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0065_auto_20230117_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selected_candidate_interview',
            name='created_at',
        ),
        migrations.AddField(
            model_name='selected_candidate_interview',
            name='current_ctc',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='selected_candidate_interview',
            name='expected_ctc',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='selected_candidate_interview',
            name='position',
            field=models.CharField(default='Not selected', max_length=30),
        ),
        migrations.AlterField(
            model_name='candidate_application',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 17, 7, 48, 16, 415551, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 17, 7, 48, 16, 415551, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 17, 7, 48, 16, 415551, tzinfo=utc)),
        ),
    ]
