# Generated by Django 3.0 on 2023-01-19 09:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0067_auto_20230117_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduled_interview',
            name='round',
            field=models.CharField(blank=True, choices=[('Round 1', 'Round 1'), ('Round 2', 'Round 2'), ('Machine Test', 'Machine Test'), ('HR Round', 'HR Round')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_application',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 19, 9, 45, 25, 855815, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 19, 9, 45, 25, 855815, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 19, 9, 45, 25, 855815, tzinfo=utc)),
        ),
    ]
