# Generated by Django 3.0 on 2023-01-19 12:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0068_auto_20230119_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduled_interview',
            name='position',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate_application',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 19, 12, 7, 41, 4763, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 19, 12, 7, 41, 4687, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 19, 12, 7, 41, 4763, tzinfo=utc)),
        ),
    ]
