# Generated by Django 3.0 on 2023-01-19 12:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0069_auto_20230119_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_application',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 19, 12, 19, 49, 846864, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 19, 12, 19, 49, 846864, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 19, 12, 19, 49, 846864, tzinfo=utc)),
        ),
    ]
