# Generated by Django 3.0 on 2023-01-23 06:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0071_auto_20230123_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_application',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 23, 6, 8, 52, 239189, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 23, 6, 8, 52, 239189, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='round',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 23, 6, 8, 52, 239189, tzinfo=utc)),
        ),
    ]
