# Generated by Django 3.0 on 2023-01-23 07:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0072_auto_20230123_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduled_interview',
            name='hr_round',
            field=models.CharField(default='Schedule', max_length=100),
        ),
        migrations.AddField(
            model_name='scheduled_interview',
            name='machine_test',
            field=models.CharField(default='Schedule', max_length=100),
        ),
        migrations.AddField(
            model_name='scheduled_interview',
            name='round2',
            field=models.CharField(blank=True, default='Schedule', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_application',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 23, 7, 47, 33, 664959, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 23, 7, 47, 33, 664959, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='round',
            field=models.CharField(blank=True, default='Schedule', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 23, 7, 47, 33, 664959, tzinfo=utc)),
        ),
    ]
