# Generated by Django 3.0 on 2023-01-23 12:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0073_auto_20230123_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduled_interview',
            old_name='round2',
            new_name='round_two',
        ),
        migrations.AlterField(
            model_name='candidate_application',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 23, 12, 43, 15, 193754, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 23, 12, 43, 15, 193754, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 23, 12, 43, 15, 193754, tzinfo=utc)),
        ),
    ]
