# Generated by Django 3.0 on 2023-02-04 05:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0074_auto_20230123_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate_application1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile_number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('years_of_experience', models.CharField(blank=True, choices=[('Fresher', 'Fresher'), ('Less than a year', 'Less than a year'), ('1 - 2 years', '1 - 2 years'), ('2 - 4 years', '2 - 4 years'), ('4 - 7 years', '4 - 7 years'), ('7 - 10 years', '7 - 10 years'), ('10+ years', '10+ years')], max_length=30, null=True)),
                ('years_of_relevant_experience', models.CharField(blank=True, choices=[('Fresher', 'Fresher'), ('Less than a year', 'Less than a year'), ('1 - 2 years', '1 - 2 years'), ('2 - 4 years', '2 - 4 years'), ('4 - 7 years', '4 - 7 years'), ('7 - 10 years', '7 - 10 years'), ('10+ years', '10+ years')], max_length=30, null=True)),
                ('resume', models.FileField(upload_to='')),
                ('department', models.CharField(blank=True, choices=[('BUSINESS_DEVELOPMENT', 'BUSINESS DEVELOPMENT'), ('DEVELOPMENT', 'DEVELOPMENT'), ('HR', 'HR'), ('TESTER', 'TESTER'), ('IMPLEMENTATION_CCMS', 'IMPLEMENTATION_CCMS'), ('CCMS_OTHER', 'CCMS OTHER'), ('IMPLEMENTATION_RFC', 'IMPLEMENTATION RFC'), ('WEB', 'WEB'), ('DIGITAL_MARKETING', 'DIGITAL MARKETING'), ('MARKETING', 'PRE-MARKETING'), ('ACCOUNTS', 'ACCOUNTS'), ('ADMIN', 'ADMIN'), ('TECH_IT', 'TECH IT'), ('MANAGEMENT', 'MANAGEMENT')], max_length=30, null=True)),
                ('position', models.CharField(default='Not selected ', max_length=30)),
                ('created_at', models.DateField(default=datetime.datetime(2023, 2, 4, 5, 36, 16, 466207, tzinfo=utc))),
                ('current_ctc', models.CharField(default='null', max_length=50)),
                ('expected_ctc', models.CharField(default='null', max_length=50)),
                ('ready_to_relocate', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Applied Candidates',
            },
        ),
        migrations.AlterField(
            model_name='candidate_application',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 2, 4, 5, 36, 16, 466207, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 2, 4, 5, 36, 16, 466207, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 2, 4, 5, 36, 16, 481792, tzinfo=utc)),
        ),
    ]
