# Generated by Django 3.0 on 2023-02-06 05:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0087_auto_20230206_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirement_master',
            options={'verbose_name_plural': 'Recruitment Master'},
        ),
        migrations.AlterField(
            model_name='candidate_application1',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 2, 6, 5, 43, 7, 249275, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='candidate_master',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 2, 6, 5, 43, 7, 249275, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement_master',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 2, 6, 5, 43, 7, 249275, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement_master',
            name='project_name',
            field=models.CharField(default='Null', max_length=40),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 2, 6, 5, 43, 7, 249275, tzinfo=utc)),
        ),
    ]
