# Generated by Django 3.0 on 2023-02-06 05:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0088_auto_20230206_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_application1',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 2, 6, 5, 47, 52, 536248, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='candidate_master',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 2, 6, 5, 47, 52, 536248, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement_master',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 2, 6, 5, 47, 52, 536248, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requirement_master',
            name='project_name',
            field=models.CharField(default='blank', max_length=40),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 2, 6, 5, 47, 52, 536248, tzinfo=utc)),
        ),
    ]
