# Generated by Django 3.0 on 2023-02-13 11:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead_app', '0103_auto_20230206_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='email',
            field=models.EmailField(default='@gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='mobile_number',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='mssda', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='pancard',
            field=models.FileField(default='j', upload_to=''),
        ),
        migrations.AlterField(
            model_name='candidate_application',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 2, 13, 11, 17, 48, 904108, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='candidate_master',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 2, 13, 11, 17, 48, 904108, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recruitment_master',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 2, 13, 11, 17, 48, 904108, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scheduled_interview',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 2, 13, 11, 17, 48, 904108, tzinfo=utc)),
        ),
    ]
