"""
Django settings for hr_recruitment project.

Generated by 'django-admin startproject' using Django 3.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m8-f0*&ull%z!6a&0#wt=7ls6os!g&j&@tczai(y$h)so*03ae'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'teamlead_app',
    "crispy_forms",
    "crispy_bootstrap5",
    'widget_tweaks',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hr_recruitment.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"], # Set the dierectory so that django can understand where to look for.
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hr_recruitment.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

#
# DATABASES = {
#      "default": {
#          'ENGINE': 'sql_server.pyodbc',
#          "NAME": "django",
#          "USER": "sa",
#          "PASSWORD": "iitms",
#          "HOST": "IITMSLP102\MSSQLSERVER2016",
#          "PORT": "",
#          "Trusted_Connection=Yes"
#          "OPTIONS":{
#              "driver":'ODBC Driver 13 for sql Server'
#          },
#      },
#  }


DATABASES = {
     "default": {
         'ENGINE': 'sql_server.pyodbc',
         "NAME": "hr_portal_django",
         "USER": "hr_portal",
         "PASSWORD": "Kbsvv@123",
         "HOST": "172.16.0.14",
         "PORT": "",
         "Trusted_Connection=Yes"
         "OPTIONS":{
             "driver":'ODBC Driver 13 for sql Server'
         },
     },
 }



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/'


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True




# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = "home/"   # On succesful log-in the user will be sent here
LOGOUT_REDIRECT_URL ="index/"



CRISPY_TEMPLATE_PACK="bootstrap4"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

# Physical system path where the static files are stored.
#STATIC_ROOT= os.path.join(BASE_DIR,'static/')
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'assets').replace('\\', '/')
# URL that your STATIC files will be accessible through the browser.


MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media/')


from django.conf.locale.es import formats as es_formats

es_formats.DATE_FORMAT = 'd-m-y'   # For saving the date in specific format


# Code for setting up the mail server
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'prathameshbhuskade.pr17@gmail.com'
EMAIL_HOST_PASSWORD = 'jplrnbnaazruyrhn'